### ISSUE TITLE
How to remove the greyed out effect on a collapsed field?

### ISSUE THREAD

**Issue by anugupta** [mrwweb/ACF-Repeater-Collapser#27]
I'm trying to work out how to remove the greyed out effect on a collapsed row (or at least make it less 'foggy').

I've noodled around the CSS and HTML with Chrome DevTools, but have had very little success, and I can't see anywhere in the javascript that would be doing it.

Any clues to where i should be looking?

![acf-collapse](https://cloud.githubusercontent.com/assets/105964/6646293/69ee7ba2-c9bb-11e4-9c18-2b19f5f37957.png)

**Comment by mrwweb** [comment]
First, make sure to take a look at the [FAQ](https://wordpress.org/plugins/advanced-custom-field-repeater-collapser/faq/) to understand what's going on:

> **Why don't rows collapse? / Why is the row only grayed out?**
> To help identify each repeater field group when collapsed, the first field of each repeated field group is shown. See the screenshots for an example.
> 
> When possible, use a short field (like a text field or dropdown) as the first row in a repeatable fieldset.

As for your specific question, the graying out is [CSS that targets the first row of the table](https://github.com/mrwweb/ACF-Repeater-Collapser/blob/master/css/acf5_repeater_collapser_admin.css#L81) when the `.collapsed-row` class is applied.

You can use the selector `.collapsed-row .acf-table tr::after` to change the visual appearance of the pseudo-element that covers that row and grays it out.

**Comment by anugupta** [comment]
Ah, of course. Thanks  :)
