### ISSUE TITLE
Nested flexible content fields - inner fields don't get collapsed

### ISSUE THREAD

**Issue by anugupta** [mrwweb/ACF-Repeater-Collapser#28]
If you nest flexible content fields, the inner nested fields don't get collapsed. They  are greyed out, but visible. They cannot be interacted with until the appropriate expand/collapse button is clicked

![window](https://cloud.githubusercontent.com/assets/105964/6678757/6da1b3f4-cc36-11e4-8f0e-64af6fc3bc35.png)

**Comment by mrwweb** [comment]
This is the expected behavior. From the FAQ:

> **Why don't rows collapse? / Why is the row only grayed out?**
To help identify each repeater field group when collapsed, **the first field of each repeated field group is shown**. See the screenshots for an example.

**Comment by anugupta** [comment]
Thanks again - I'm not usually this slow to grok stuff :)
