### ISSUE TITLE
No collapsing with latest version of ACF Pro (5.2.7) 

### ISSUE THREAD

**Issue by anugupta** [mrwweb/ACF-Repeater-Collapser#30]
Just updated ACF to 5.2.7, and the collapse buttons are no longer appearing on flex content or repeater fields

**Comment by markrummel** [comment]
I'm experiencing the same issue with ACF 5.2.7.

**Comment by SmashBrando** [comment]
Same on 5.2.8

**Comment by mrwweb** [comment]
https://wordpress.org/support/topic/acf-pro-527-temporary-fix-support-delay

-----------------------------------

Tiny keyboards are a leading cause of short messages, odd word choice, and
typos.

**Comment by anugupta** [comment]
Confirming that this temporary fix works - thanks.

**Comment by mrwweb** [comment]
This was resolved in 1.4.2
