### ISSUE TITLE
Undefined index: class Error

### ISSUE THREAD

**Issue by A-0-0-P** [mrwweb/ACF-Repeater-Collapser#34]
I'm getting this error below each repeater or flexible content field (3x always):

Notice: Undefined index: class in /www/quractiv/wp-content/plugins/advanced-custom-fields-pro/core/compatibility.php on line 137

ACF 5.3.0 / ACF Field Collapser 1.4.2 / WP 4.3
wp-config.php -> define('WP_DEBUG', true);
![screen shot 2015-09-10 at 15 31 25](https://cloud.githubusercontent.com/assets/14233461/9813200/ded08116-5883-11e5-909f-5dcbc8dd1aec.png)

**Comment by mrwweb** [comment]
Are you sure that's an ACF Repeater Collapser bug? The error looks to me
like a problem in ACF PRO. Please submit a bug report to their support and
then get back to me if you know for sure it's an issue with this plugin.

**Comment by A-0-0-P** [comment]
Ok Mark, will do & get back to you.

**Comment by mmjaeger** [comment]
getting the same error

**Comment by JulienMelissas** [comment]
Yep - this is an error that is only coming up when the repeater collapser plugin is activated. I'm going to see if I can figure out what's wrong really quick here...

**Comment by JulienMelissas** [comment]
So I did a little digging, it seems that in ACF PRO 5.2.7 there were a few changes. Without having a ton of time to look into them, in the changelog it says:
>* Core: Changed compatibility filter default to false

You can see the difference between the 2 versions here: https://www.dropbox.com/s/jhgax86pfr74rt6/Screenshot%202015-09-13%2013.15.57.png?dl=0 (version 5.2.6 is on the left, current is on the right)

I don't know enough about the core functionality to know if it's safe, but the issue does seem to go away if I remove these lines: https://github.com/mrwweb/ACF-Repeater-Collapser/blob/master/acf_repeater_collapser.php#L50-L53

The other thing we could do is change the check to only work between versions 5.0.0 and 5.2.6, that might be a safer bet.

Would you like me to make a PR?

**Comment by JulienMelissas** [comment]
Actually, looking a little deeper, I'm seeing that the blog post you linked to from them (http://www.advancedcustomfields.com/blog/acf-pro-5-2-7-update/) recommended that you add that block of code. Hmmm.

Pinging @elliotcondon, unless there's a better way to get in touch with them?

**Comment by JulienMelissas** [comment]
Sorry, not trying to spam, but just to mention if it wasn't clear: this error only shows up when you're trying to edit custom fields - not where the ACF Repeater Collapser actually shows up:
https://www.dropbox.com/s/l8wiaezwm74qoxo/Screenshot%202015-09-13%2013.36.32.png?dl=0

(and it's on any type of field, tabs, repeaters, etc)

**Comment by elliotcondon** [comment]
Hi guys,

Thanks for the bug report.
This is indeed an issue from the ACF PRO plugin, and has just been fixed.
I'll include the fix in the next version.

Cheers
E

**Comment by A-0-0-P** [comment]
Thanks, Elliot ! And Julien, for taking as well time to look into it. Cheers!

**Comment by mrwweb** [comment]
Thanks for the update, @elliotcondon. Closing this issue here.

**Comment by JulienMelissas** [comment]
Thanks for the fix @elliotcondon! I'm assuming we won't have to make any changes over here?

**Comment by elliotcondon** [comment]
Hi @JulienMelissas 

No changes needed

**Comment by 0161-Jon** [comment]
Hi, I am getting this exact error but am using the most recent version of ACF PRO Version 5.3.0.

Any idea how I can fix this please?

**Comment by elliotcondon** [comment]
Hi @0161-Jon 

The latest version is 5.3.2.2 - please upgrade and this issue will be fixed

**Comment by 0161-Jon** [comment]
Hi @elliotcondon, weird, the site in question isn't showing update available in the plugins page. If I click on the updates link within ACF menu it showed no update available, I re checked and it shows update available, click update and nothing happens, still the old version in the plugins page with no update link?

The license is valid and active and in use on several other sites which have all updated fine (I have dev license).

Any ideas please?

Thanks!

**Comment by elliotcondon** [comment]
Hi @0161-Jon 

If you other sites can upgrade to the latest, use them to download the files, then copy the plugin files from 1 site to the other.

You can also download plugin files from your my-account section:
http://www.advancedcustomfields.com/my-account
