### ISSUE TITLE
I dont see the repeater in the field type

### ISSUE THREAD

**Issue by waisie** [mrwweb/ACF-Repeater-Collapser#37]
I don't see the repeater in the field type. Where is the repeater ?

**Comment by waisie** [comment]
I install the Advanced Custom Fields. Do I still need to purchase The Repeater Field?

**Comment by mrwweb** [comment]
This is a free plugin that adds a single feature to the Advanced Custom Fields Repeater Field. That field is only available in Advanced Custom Fields PRO. Please contact Advanced Custom Fields support if you need assistance with that plugin.
