### ISSUE TITLE
Unaligned 'Collapse All' button and no individual collapse

### ISSUE THREAD

**Issue by lewebsimple** [mrwweb/ACF-Repeater-Collapser#45]
Using the latest ACF PRO (5.6.1), it seems the collapse all button is unaligned (see screenshot below)
![collapse-all](https://user-images.githubusercontent.com/23109383/29086371-5c51730c-7c40-11e7-9d7e-1385300e49ed.jpg)

Also the individual collapse buttons don't appear at all (using the row layout as stated in the readme).

Any ideas?

**Comment by eberhapa** [comment]
#46 I made a pull request to resolve this issue. You can fix it by yourself by include a custom admin.css and setting top: 0 and right: 0 on .collapse class.
